sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t my_image .

script:
  - docker run -e CI=true my_image npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "udemy-course-v2"
  env: "รง"
  bucket_name: "elasticbeanstalk-us-east-2-881778425398"
  bucket_path: "udemy-course-v2"
  on:
    branch: main
